# Generated by Django 6.0.7 on 2026-08-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя в Telegram')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Никнейм (@username)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('is_terms_accepted', models.BooleanField(default=False, verbose_name='Согласен с обработкой ПД?')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время принятия согласия')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название салона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон филиала')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название процедуры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб.)')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Длительность (в минутах)')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО Мастера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает сейчас в сети?')),
                ('salons', models.ManyToManyField(to='bot_manager.salon', verbose_name='В каких салонах работает')),
                ('services', models.ManyToManyField(to='bot_manager.service', verbose_name='Какие процедуры делает')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время начала приема')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Слот уже забронирован?')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manager.master', verbose_name='Мастер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manager.salon', verbose_name='Салон, где принимает мастер в этот день')),
            ],
            options={
                'verbose_name': 'Свободное окно (Слот)',
                'verbose_name_plural': 'Расписание (Слоты)',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('completed', 'Визит завершен'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус записи')),
                ('tips_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Чаевые мастера (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manager.client', verbose_name='Клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_manager.service', verbose_name='Услуга')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bot_manager.timeslot', verbose_name='Выбранное время и мастер')),
            ],
            options={
                'verbose_name': 'Запись на процедуру',
                'verbose_name_plural': 'Записи на процедуры',
            },
        ),
    ]
