# Generated by Django 6.0.7 on 2026-08-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время онлайн-оплаты'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер транзакции (имитация)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('sbp', 'СБП')], max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
