# Generated by Django 6.0.7 on 2026-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="Текст отзыва"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="feedback_asked",
            field=models.BooleanField(
                default=False, verbose_name="Уже спрашивали отзыв?"
            ),
        ),
    ]
