# Generated by Django 6.0.7 on 2026-07-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_manager", "0002_appointment_feedback_appointment_feedback_asked"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="discount_applied",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Скидка (руб.)",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="promo_code_used",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Примененный промокод",
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код промокода"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Процентная скидка"),
                            ("fixed", "Фиксированная скидка (руб.)"),
                        ],
                        default="percent",
                        max_length=20,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Значение скидки"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Действует с")),
                ("valid_to", models.DateTimeField(verbose_name="Действует до")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        default=0, verbose_name="Лимит использований (0 - безлимит)"
                    ),
                ),
                (
                    "used_count",
                    models.IntegerField(
                        default=0, verbose_name="Сколько раз использован"
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        to="bot_manager.service",
                        verbose_name="Применяется к услугам (если пусто - ко всем)",
                    ),
                ),
            ],
        ),
    ]
