# Generated by Django 6.0.7 on 2026-08-01 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0003_promocode_appointment_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка (1–5)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manager.appointment', verbose_name='Запись')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manager.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manager.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'constraints': [models.UniqueConstraint(fields=('appointment',), name='unique_review_per_appointment')],
            },
        ),
    ]
