# Generated by Django 6.0.7 on 2026-08-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tips_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время оплаты чаевых'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tips_payment_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер транзакции чаевых (имитация)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tips_payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('sbp', 'СБП')], max_length=20, null=True, verbose_name='Способ оплаты чаевых'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tips_token',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Токен ссылки на чаевые'),
        ),
    ]
